version: 2
updates:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "daily"

  - package_manager: "dotnet:nuget"
    directory: "/Tailspin.SpaceGame.LeaderboardContainer/"
    update_schedule: "daily"

  - package_manager: "dotnet:nuget"
    directory: "/Tailspin.SpaceGame.Web/"
    update_schedule: "daily"
