name: Spacegame.ACR

on:
  workflow_dispatch:

jobs:
  leaderboardpush:
    name: ðŸ“¦ Deploy to ACR - API
    runs-on: ubuntu-latest    
    steps:
      
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Login to Azure Container Registry
        uses: docker/login-action@v1
        with:
          registry: darquewarrior.azurecr.io
          username: darquewarrior
          password: ${{ secrets.ACR_PASSWORD }}
          
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y.%m.%d')"
        
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Tailspin.SpaceGame.LeaderboardContainer/Dockerfile
          push: true
          tags: |
            darquewarrior.azurecr.io/leaderboard:latest
            darquewarrior.azurecr.io/leaderboard:${{ steps.date.outputs.date }}.${{ github.run_number }}
       
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  spacegamepush:
    name: ðŸ“¦ Deploy to ACR - Web
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Login to Azure Container Registry
        uses: docker/login-action@v1
        with:
          registry: darquewarrior.azurecr.io
          username: darquewarrior
          password: ${{ secrets.ACR_PASSWORD }}
          
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y.%m.%d')"
      
      - name: Configure App Settings
        uses: cschleiden/replace-tokens@v1
        with: 
         files: '["Tailspin.SpaceGame.Web/appsettings.json"]'
        env:
         LEADERBOARD_API_URL: ${{secrets.API_CLUSTER_IP}}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Tailspin.SpaceGame.Web/Dockerfile
          push: true
          tags: |
            darquewarrior.azurecr.io/spacegameweb:latest
            darquewarrior.azurecr.io/spacegameweb:${{ steps.date.outputs.date }}.${{ github.run_number }}
          
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
