# This is a basic workflow to help you get started with Actions

name: JIRA Test

# Controls when the workflow will run
on:
  issues:
    types: [opened,closed]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  issuecreation:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    if: github.event.issue.opened 

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access i
     
      - name: Login
        uses: atlassian/gajira-login@master
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

      - name: Creating Jira Issue
        uses: atlassian/gajira-create@v2.0.1
        with:
         project: COOP
         issuetype: Task
         summary: ${{github.event.issue.title}}
         description: ${{github.event.issue.body}}
         fields: '{"assignee": "${{github.event.issue.assignee}}"}' # not working
        env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
  issueclose:
    runs-on: ubuntu-latest
    if: github.event.issue.closed 
    steps:
    
    - name: Transition issue
      uses: atlassian/gajira-transition@master
      with:
        issue: ${{github.event.issue.title}}
        transition: "In progress"
