name: manage-azure-policy-a6c4c747
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/Latest_TLS_version_should_be_used_in_your_Web_App_f0e6e85b-9b9f-4a4b-b67b-f730d42f1b0b/**'
#      - 'policies/Web_apps_should_use_an_Azure_file_share_for_its_content_directory_dcbc65aa-59f3-4239-8978-3bb869d82604/**'
#      - 'policies/Remote_debugging_should_be_turned_off_for_Web_Applications_cb510bfd-1cba-4d9f-a230-cb0976f4bb71/**'
#      - 'policies/Managed_identity_should_be_used_in_your_Web_App_2b9ad585-36bc-4615-b300-fd4435808332/**'
#      - 'policies/FTPS_should_be_required_in_your_Web_App_4d24b6d4-5e53-4a4f-a7f4-618fa573ee4b/**'
#      - 'policies/CORS_should_not_allow_every_resource_to_access_your_Web_Applications_5744710e-cc2f-4ee8-8809-3b11e89f4bc9/**'
#      - 'policies/Ensure_WEB_app_has_Client_Certificates_(Incoming_client_certificates)_set_to_On_5bb220d9-2698-4ee4-8404-b9c30c9df609/**'
#      - 'policies/Ensure_that_Python_version_is_the_latest,_if_used_as_a_part_of_the_Web_app_7008174a-fd10-4ef0-817e-fc820a951d73/**'
#      - 'policies/Ensure_that_PHP_version_is_the_latest,_if_used_as_a_part_of_the_WEB_app_7261b898-8a84-4db8-9e04-18527132abb3/**'
#      - 'policies/Ensure_that_HTTP_Version_is_the_latest,_if_used_to_run_the_Web_app_8c122334-9d20-4eb8-89ea-ac9a705b74ae/**'
#      - 'policies/Resource_logs_in_App_Services_should_be_enabled_91a78b24-f231-4a8a-8da9-02c35b2b6510/**'
#      - 'policies/Authentication_should_be_enabled_on_your_web_app_95bccee9-a7f8-4bec-9ee9-62c3473701fc/**'
#      - 'policies/Web_Application_should_only_be_accessible_over_HTTPS_a4af4a39-4135-47fb-b175-47fbdf85311d/**'
#      - .github/workflows/manage-azure-policy-a6c4c747.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_a6c4c747}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/Latest_TLS_version_should_be_used_in_your_Web_App_f0e6e85b-9b9f-4a4b-b67b-f730d42f1b0b/**
          policies/Web_apps_should_use_an_Azure_file_share_for_its_content_directory_dcbc65aa-59f3-4239-8978-3bb869d82604/**
          policies/Remote_debugging_should_be_turned_off_for_Web_Applications_cb510bfd-1cba-4d9f-a230-cb0976f4bb71/**
          policies/Managed_identity_should_be_used_in_your_Web_App_2b9ad585-36bc-4615-b300-fd4435808332/**
          policies/FTPS_should_be_required_in_your_Web_App_4d24b6d4-5e53-4a4f-a7f4-618fa573ee4b/**
          policies/CORS_should_not_allow_every_resource_to_access_your_Web_Applications_5744710e-cc2f-4ee8-8809-3b11e89f4bc9/**
          policies/Ensure_WEB_app_has_Client_Certificates_(Incoming_client_certificates)_set_to_On_5bb220d9-2698-4ee4-8404-b9c30c9df609/**
          policies/Ensure_that_Python_version_is_the_latest,_if_used_as_a_part_of_the_Web_app_7008174a-fd10-4ef0-817e-fc820a951d73/**
          policies/Ensure_that_PHP_version_is_the_latest,_if_used_as_a_part_of_the_WEB_app_7261b898-8a84-4db8-9e04-18527132abb3/**
          policies/Ensure_that_HTTP_Version_is_the_latest,_if_used_to_run_the_Web_app_8c122334-9d20-4eb8-89ea-ac9a705b74ae/**
          policies/Resource_logs_in_App_Services_should_be_enabled_91a78b24-f231-4a8a-8da9-02c35b2b6510/**
          policies/Authentication_should_be_enabled_on_your_web_app_95bccee9-a7f8-4bec-9ee9-62c3473701fc/**
          policies/Web_Application_should_only_be_accessible_over_HTTPS_a4af4a39-4135-47fb-b175-47fbdf85311d/**
